---
name: Run a basic openQA test
# yamllint disable-line rule:truthy
on:
  pull_request:
  # Note how this runs on:pull_request_target and not on:pull_request!
  # The difference is that this runs always with the context of the master
  # branch. This is necessary to allow accessing the API credential secrets.
  workflow_dispatch:
env:
  OPENQA_HOST: ${{ secrets.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  GH_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  GH_REF: ${{ github.event.pull_request.head.ref }}
  GH_PR_BODY: ${{ github.event.pull_request.body }}

jobs:
  clone_mentioned_job:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - name: Clone and monitor job mentioned in PR description
        uses: Martchus/scripts/actions/clone-job@gh-action-test
