---
name: Clone an openQA test mentioned in a PR comment
# yamllint disable-line rule:truthy
on:
  issue_comment:
    types: [created, edited]
env:
  OPENQA_HOST: ${{ vars.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  GH_PR_URL: ${{ github.event.issue.pull_request.url }}
  GH_COMMENT_BODY: ${{ github.event.comment.body }}
  GH_COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
  GH_COMMENT_URL: ${{ github.event.comment.html_url }}
  RESTRICT_ORGA: os-autoinst
  RESTRICT_TEAM: tests-maintainer

jobs:
  clone_mentioned_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      GITHUB_TOKEN_DEFAULT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.CLASSIC_TOKEN_FOR_TESTS }}
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - name: Clone and monitor job mentioned in PR comment
        uses: Martchus/scripts/actions/clone-job@clone-on-comment
